let readlineSync = require('readline-sync');
let age = Number(readlineSync.question('How old are you?\n'));
let step = 10;
console.log(`You are ${age} years old.`);
console.log(`In ${step} years, you will be ${age + step} years old.`);
step += 10;
console.log(`In ${step} years, you will be ${age + step} years old.`);
step += 10;
console.log(`In ${step} years, you will be ${age + step} years old.`);
step += 10;
console.log(`In ${step} years, you will be ${age + step} years old.`);
